### ISSUE TITLE
Richfaces 4.5.0.Final

### ISSUE THREAD

**Issue by yanLanglois** [rdicroce/jsfexporter#31]
In order to make this exporter works whith RichFaces 4.5.0.Final, I had to exclude RichFaces dependencies. Like this :
```xml
        <dependency>
		    <groupId>com.lapis.jsfexporter</groupId>
		    <artifactId>export-source-richfaces</artifactId>
		    <version>1.0.2.Final</version>
		    <exclusions>
		    	<exclusion>
		    		<artifactId>richfaces-components-ui</artifactId>
		    		<groupId>org.richfaces.ui</groupId>
		    	</exclusion>
		    </exclusions>
		</dependency>
```
It could be a good idea to mark the dependency as provided. I think there is the same problem with primefaces...

**Comment by rdicroce** [comment]
Closing this - won't fix. Developers are obviously free to use whatever version of the component library they want to, but the exporter was compiled against a specific version. So IMO this should remain a compile scope dependency.

The real issue is that the RichFaces developers changed their Maven artifact structure. I just released exporter version 1.0.3.Final, which included bumping RF to 4.5.2.Final and adjusting for the new RF artifact structure.
